[package]
name = "reonix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comp = "0.2.1"
rand = "0.8.5"
round = "0.1.2"
